### ISSUE TITLE
Bun?

### ISSUE THREAD

**Issue by jacksongoode** [pulse-browser/experiment#16]
Any reason not to use bun as the package manager/builder?

**Comment by trickypr** [comment]
This app uses file system hot reloading. The system that I have gotten that works best with this is webpack. Given the fact that it works and is fast enough for my use cases, I am not going to switch away from it for the moment.

Maybe in the future if there is some specific use case that bun would make easier I would consider using it. However, most dev time goes into messing with mozilla apis that never touch nodejs or pnpm, so bun wouldn't provide any benefit.
